DROP DATABASE IF EXISTS LAVAMASS;
CREATE DATABASE LAVAMASS;

USE LAVAMASS;

DROP TABLE IF EXISTS CUSTOMERS;
CREATE TABLE CUSTOMERS
(
  COD TINYINT AUTO_INCREMENT PRIMARY KEY,
  DNI CHAR(8) UNIQUE NOT NULL ,
  NAME VARCHAR(80) NOT NULL,
  LASTNAME VARCHAR(80) NOT NULL,
  TELF VARCHAR(12) NOT NULL,
  ADRESS VARCHAR(120),
  EMAIL VARCHAR(120) NOT NULL
)ENGINE = INNODB, CHARSET = UTF8;

DROP TABLE IF EXISTS SERVICES;
CREATE TABLE SERVICES
(
  COD TINYINT AUTO_INCREMENT PRIMARY KEY,
  DESCRIPTION VARCHAR(80) NOT NULL,
  UNID VARCHAR(20) NOT NULL,
  REG_PRICE DOUBLE(5,2) NOT NULL
)ENGINE = INNODB, CHARSET = UTF8;

DROP TABLE IF EXISTS JOB_ORDERS;
CREATE TABLE JOB_ORDERS
(
  ORDER_NUMBER INT AUTO_INCREMENT PRIMARY KEY,
  CUSTOMER_DNI CHAR(8),
  ORDER_DATE DATETIME,
  DELIVER_DATE DATETIME,
  STATUS CHAR(2),
  CONSTRAINT FK_CUSTOMER_ORDER FOREIGN KEY (CUSTOMER_DNI) REFERENCES CUSTOMERS(DNI)
)ENGINE = INNODB, CHARSET = UTF8;

DROP TABLE IF EXISTS ORDER_DETAIL;
CREATE TABLE ORDER_DETAIL
(
  ORDER_NUMBER INT NOT NULL,
  COD_SERVICE TINYINT NOT NULL,
  QUANTITY DOUBLE(3,1) NOT NULL,
  COMMENT VARCHAR(200),
  CONSTRAINT PK_DETAIL_ORDER PRIMARY KEY (ORDER_NUMBER),
  CONSTRAINT FK_DETAIL_ORDER FOREIGN KEY (ORDER_NUMBER) REFERENCES JOB_ORDERS(ORDER_NUMBER),
  CONSTRAINT FK_SERVICE_ORDER FOREIGN KEY (COD_SERVICE) REFERENCES SERVICES(COD)
)ENGINE = INNODB, CHARSET = UTF8;

DROP TABLE IF EXISTS SELL_TICKETS;
CREATE TABLE SELL_TICKETS
(
  TICKET_NUMBER INT PRIMARY KEY AUTO_INCREMENT,
  ORDER_NUMBER INT NOT NULL,
  GROSS_PRICE DOUBLE(5,2),
  IGV DOUBLE(5,2),
  DISCOUNT DOUBLE(5,2),
  TOTAL_PRICE DOUBLE(5,2),
  SELL_DATE DATETIME,
  PAY_DATE DATETIME,
  STATUS CHAR(2),
  CONSTRAINT FK_TICKETS_ORDERS FOREIGN KEY (ORDER_NUMBER) REFERENCES JOB_ORDERS(ORDER_NUMBER)
)ENGINE = INNODB, CHARSET = UTF8;


DROP TABLE IF EXISTS DETAIL_TICKET;
CREATE TABLE DETAIL_TICKET
(
  TICKET_NUMBER INT NOT NULL,
  ITEM_NUMBER TINYINT,
  SERVICE_CODE TINYINT NOT NULL,
  QUANTITY DOUBLE(3,1) NOT NULL,
  SUBTOTAL DOUBLE(5,2) NOT NULL,
  COMMENT VARCHAR(200),
  CONSTRAINT UNQ_SEQUENCE_DETAIL UNIQUE (TICKET_NUMBER, ITEM_NUMBER),
  CONSTRAINT PK_TICKET_DETAIL PRIMARY KEY (TICKET_NUMBER),
  CONSTRAINT FK_TICKET_DETAIL FOREIGN KEY (TICKET_NUMBER) REFERENCES SELL_TICKETS(TICKET_NUMBER)
)ENGINE = INNODB, CHARSET = UTF8;
