DROP DATABASE IF EXISTS LAVAMASS;
CREATE DATABASE LAVAMASS;

USE LAVAMASS;

DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS
(
  REL_ID INT AUTO_INCREMENT PRIMARY KEY,
  COD CHAR(10) UNIQUE NOT NULL,
  DNI CHAR(8) UNIQUE NOT NULL,
  PASSWD NVARCHAR(200) NOT NULL,
  NAME VARCHAR(80) NOT NULL,
  LASTNAME VARCHAR(80) NOT NULL,
  TELF VARCHAR(12) NOT NULL,
  ADRESS VARCHAR(120),
  EMAIL VARCHAR(120) NOT NULL,
#   USER_TYPE CHAR(1) NOT NULL,
  REGISTRY_DATE TIMESTAMP
)ENGINE = INNODB, CHARSET = UTF8;

DROP TABLE IF EXISTS SERVICES;
CREATE TABLE SERVICES
(
  COD TINYINT AUTO_INCREMENT PRIMARY KEY,
  DESCRIPTION VARCHAR(80) NOT NULL,
  UNID VARCHAR(20) NOT NULL,
  REG_PRICE DOUBLE(5,2) NOT NULL
)ENGINE = INNODB, CHARSET = UTF8;

DROP TABLE IF EXISTS JOB_ORDERS;
CREATE TABLE JOB_ORDERS
(
  ORDER_NUMBER INT AUTO_INCREMENT PRIMARY KEY,
  CUSTOMER_ID INT,
  ORDER_DATE TIMESTAMP,
  DELIVER_DATE TIMESTAMP,
  STATUS CHAR(2),
  REGISTRY_USER CHAR(8) NOT NULL,
  CONSTRAINT FK_CUSTOMER_ORDER FOREIGN KEY (CUSTOMER_ID) REFERENCES USERS(REL_ID)
)ENGINE = INNODB, CHARSET = UTF8;

DROP TABLE IF EXISTS ORDER_DETAIL;
CREATE TABLE ORDER_DETAIL
(
  ORDER_NUMBER INT NOT NULL,
  COD_SERVICE TINYINT NOT NULL,
  QUANTITY DOUBLE(3,1) NOT NULL,
  COMMENT VARCHAR(200),
  CONSTRAINT PK_DETAIL_ORDER PRIMARY KEY (ORDER_NUMBER),
  CONSTRAINT FK_DETAIL_ORDER FOREIGN KEY (ORDER_NUMBER) REFERENCES JOB_ORDERS(ORDER_NUMBER),
  CONSTRAINT FK_SERVICE_ORDER FOREIGN KEY (COD_SERVICE) REFERENCES SERVICES(COD)
)ENGINE = INNODB, CHARSET = UTF8;

DROP TABLE IF EXISTS SELL_TICKETS;
CREATE TABLE SELL_TICKETS
(
  TICKET_NUMBER INT PRIMARY KEY AUTO_INCREMENT,
  ORDER_NUMBER INT NOT NULL,
  CUSTOMER_DNI INT NOT NULL,
  GROSS_PRICE DOUBLE(5,2),
  IGV DOUBLE(5,2),
  DISCOUNT DOUBLE(5,2),
  TOTAL_PRICE DOUBLE(5,2),
  SELL_DATE TIMESTAMP,
  PAY_DATE TIMESTAMP,
  STATUS CHAR(2),
  CONSTRAINT FK_TICKETS_ORDERS FOREIGN KEY (ORDER_NUMBER) REFERENCES JOB_ORDERS(ORDER_NUMBER)
)ENGINE = INNODB, CHARSET = UTF8;

DROP TABLE IF EXISTS DETAIL_TICKET;
CREATE TABLE DETAIL_TICKET
(
  TICKET_NUMBER INT NOT NULL,
  ITEM_NUMBER TINYINT,
  SERVICE_CODE TINYINT NOT NULL,
  QUANTITY DOUBLE(3,1) NOT NULL,
  SUBTOTAL DOUBLE(5,2) NOT NULL,
  COMMENT VARCHAR(200),
  CONSTRAINT UNQ_SEQUENCE_DETAIL UNIQUE (TICKET_NUMBER, ITEM_NUMBER),
  CONSTRAINT PK_TICKET_DETAIL PRIMARY KEY (TICKET_NUMBER),
  CONSTRAINT FK_TICKET_DETAIL FOREIGN KEY (TICKET_NUMBER) REFERENCES SELL_TICKETS(TICKET_NUMBER)
)ENGINE = INNODB, CHARSET = UTF8;

DROP TABLE IF EXISTS ROLES;
CREATE TABLE ROLES
(
  ROL_ID TINYINT PRIMARY KEY AUTO_INCREMENT,
  ROL_NAME VARCHAR(80)
)ENGINE = INNODB, CHARSET = UTF8;

DROP TABLE IF EXISTS USER_ROLES;
CREATE TABLE USER_ROLES
(
  ROL_ID TINYINT NOT NULL,
  USER_COD INT NOT NULL,
  CONSTRAINT FK_ROL FOREIGN KEY (ROL_ID) REFERENCES ROLES(ROL_ID),
  CONSTRAINT FK_USER FOREIGN KEY (USER_COD) REFERENCES USERS(REL_ID),
  CONSTRAINT PK_USERS_ROLES PRIMARY KEY (ROL_ID, USER_COD)
)ENGINE = INNODB, CHARSET = UTF8;

DROP TABLE IF EXISTS PARAMS;
CREATE TABLE PARAMS
(
  PARAM_ID CHAR(5) PRIMARY KEY NOT NULL,
  PARAM_GROUP VARCHAR(20) NOT NULL,
  PARAM_DESC VARCHAR(80) NOT NULL
)ENGINE = INNODB, CHARSET = UTF8;
